version: "3"
services:
  api:
    image: osinn-admin-vben-api
    container_name: osinn-admin-vben-api
    restart: always
    ports:
      - "9990:9990"
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./api/logs:/app/logs
    networks:
      - osinn-admin-vben-network
    depends_on:
      - mysql
      - redis

  redis:
    container_name: osinn-admin-vben-redis
    restart: always
    image: redis:8.4.0
    ports:
      - "6399:6379"
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - ./redis/data:/data
    environment:
      TZ: "Asia/Shanghai"
    networks:
      - osinn-admin-vben-network
    command: redis-server /etc/redis/redis.conf

  mysql:
    container_name: osinn-admin-vben-mysql
    restart: always
    image: mysql:5.7.44
    ports:
      - "3366:3306"
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d # mysql 初始化创建数据库
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - osinn-admin-vben-network

networks:
  osinn-admin-vben-network:
    driver: bridge

volumes: {}